#cloud-config
packages:
- git
- openssl
- unzip
runcmd:
- git clone https://github.com/colstrom/ops-consul /opt/ops-consul
- echo /opt/ops-consul | /opt/ops-consul/scripts/install
- echo /opt/ops-consul | /opt/ops-consul/scripts/configure
