#cloud-config
packages:
- unzip
runcmd:
- wget -q -O /tmp/consul.zip https://releases.hashicorp.com/consul/0.6.4/consul_0.6.4_linux_amd64.zip
- unzip /tmp/consul.zip -d /usr/local/bin
- rm -vf /tmp/consul.zip
- wget -q -O /etc/systemd/system/consul.service https://raw.githubusercontent.com/colstrom/ops-consul/master/systemd/consul.service
- mkdir -p /etc/consul.d/
- touch /etc/sysconfig/consul
- systemctl daemon-reload
- systemctl enable consul
- systemctl start consul
